### ISSUE TITLE
Twitter Login native not working after authorize within the native app

### ISSUE THREAD

**Issue by hgouveia** [BlupGithub/social_login_3#1]
Hello, after i log in and Authorize the app within the native twitter app, the Future is never resolved, 

i don't have any error logs or anything but as soon i clicked "Authorized App" in the native twitter app, it sends me back to my App, and i have a little toast that said "Operation not permitted" or something like this, 

My code is fairly simple 

version `social_login_3: ^0.1.1`
```dart
import 'package:social_login_3/social_login_3.dart';

const String CONSUMER_KEY = '';
const String CONSUMER_SECRET = '';

final socialLogin = SocialLogin();

socialLogin.setConfig(SocialConfig(
   twitterConsumer: CONSUMER_KEY,
   twitterSecret: CONSUMER_SECRET,
));

try {
    final TwitterUser twitterUser = await socialLogin.logInTwitter();
    print(twitterUser); // never reach it
} catch (err) {
    print(err); // never reach it
}
```

**Comment by SahajRana** [comment]
Hi @hgouveia , I have updated the lib social_login_3: `^0.1.2`. It now supports standalone social login.

**Comment by hgouveia** [comment]
> Hi @hgouveia , I have updated the lib social_login_3: `^0.1.2`. It now supports standalone social login.

hey @SahajRana  thanks for your quick reply, i upgraded, and now it goes to the **Catch** , and gave me this error

```
PlatformException(400, Authorize failed., null)
```
I've checked my consumer key and secret and both are correct

**Comment by SahajRana** [comment]
@hgouveia Did you receive any more elaborated error? 
I have not used Twitter login personally in my project. So, I'm not sure where the error could be. 

I have only tested for Google login.

If there is a problem in the library then you can let me know or make a `pull request` and I can merge it.

**Comment by meghead** [comment]
I've got a similar problem in Android Studio using  social_login_3: ^0.1.2;

PlatformException(400, Failed to get request token, null, null)

using this code:

Future<void> logInTwitter(BuildContext context) async {
    try {
      socState();
      currentUser = await socialLogin.logInTwitter();
      print(currentUser);

**Comment by SahajRana** [comment]
Hi @meghead, thanks for the comment. I will look into it in the coming weekdays.

**Comment by meghead** [comment]
If it helps, here is some more error information I'm getting in Android Studio's console;

W/hin.speakoholi(22181): Accessing hidden method Lcom/android/org/conscrypt/ConscryptEngineSocket;->setUseSessionTickets(Z)V (greylist-max-q,core-platform-api, reflection, denied)
W/hin.speakoholi(22181): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setUseSessionTickets(Z)V (greylist-max-q,core-platform-api, reflection, denied)
W/hin.speakoholi(22181): Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->setUseSessionTickets(Z)V (greylist-max-q, reflection, denied)
W/hin.speakoholi(22181): Accessing hidden method Lcom/android/org/conscrypt/ConscryptEngineSocket;->setHostname(Ljava/lang/String;)V (greylist-max-q,core-platform-api, reflection, denied)
W/hin.speakoholi(22181): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setHostname(Ljava/lang/String;)V (greylist-max-q,core-platform-api, reflection, denied)
W/hin.speakoholi(22181): Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->setHostname(Ljava/lang/String;)V (greylist-max-q, reflection, denied)
W/hin.speakoholi(22181): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setAlpnProtocols([B)V (greylist-max-q,core-platform-api, reflection, denied)
W/hin.speakoholi(22181): Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->setAlpnProtocols([B)V (greylist-max-q, reflection, denied)
W/hin.speakoholi(22181): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B (greylist-max-q,core-platform-api, reflection, denied)
W/hin.speakoholi(22181): Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->getAlpnSelectedProtocol()[B (greylist-max-q, reflection, denied)
E/Twitter (22181): Invalid json: <?xml version='1.0' encoding='UTF-8'?><errors><error code="415">Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings</error></errors>
E/Twitter (22181): com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
E/Twitter (22181): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
E/Twitter (22181): 	at com.twitter.sdk.android.core.models.SafeListAdapter$1.read(SafeListAdapter.java:45)
E/Twitter (22181): 	at com.twitter.sdk.android.core.models.SafeMapAdapter$1.read(SafeMapAdapter.java:45)
E/Twitter (22181): 	at com.google.gson.Gson.fromJson(Gson.java:932)
E/Twitter (22181): 	at com.google.gson.Gson.fromJson(Gson.java:897)
E/Twitter (22181): 	at com.google.gson.Gson.fromJson(Gson.java:846)
E/Twitter (22181): 	at com.google.gson.Gson.fromJson(Gson.java:817)
E/Twitter (22181): 	at com.twitter.sdk.android.core.TwitterApiException.parseApiError(TwitterApiException.java:110)
E/Twitter (22181): 	at com.twitter.sdk.android.core.TwitterApiException.readApiError(TwitterApiException.java:95)
E/Twitter (22181): 	at com.twitter.sdk.android.core.TwitterApiException.<init>(TwitterApiException.java:43)
E/Twitter (22181): 	at com.twitter.sdk.android.core.Callback.onResponse(Callback.java:42)
E/Twitter (22181): 	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
E/Twitter (22181): 	at android.os.Handler.handleCallback(Handler.java:938)
E/Twitter (22181): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/Twitter (22181): 	at android.os.Looper.loop(Looper.java:223)
E/Twitter (22181): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/Twitter (22181): 	at java.lang.reflect.Method.invoke(Native Method)
E/Twitter (22181): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/Twitter (22181): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/Twitter (22181): Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
E/Twitter (22181): 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386)
E/Twitter (22181): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
E/Twitter (22181): 	... 18 more
E/Twitter (22181): Failed to get request token
E/Twitter (22181): com.twitter.sdk.android.core.TwitterApiException: HTTP request failed, Status: 403
E/Twitter (22181): 	at com.twitter.sdk.android.core.Callback.onResponse(Callback.java:42)
E/Twitter (22181): 	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
E/Twitter (22181): 	at android.os.Handler.handleCallback(Handler.java:938)
E/Twitter (22181): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/Twitter (22181): 	at android.os.Looper.loop(Looper.java:223)
E/Twitter (22181): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/Twitter (22181): 	at java.lang.reflect.Method.invoke(Native Method)
E/Twitter (22181): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/Twitter (22181): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/Twitter (22181): Authorization completed with an error
E/Twitter (22181): com.twitter.sdk.android.core.TwitterAuthException: Failed to get request token
E/Twitter (22181): 	at com.twitter.sdk.android.core.identity.OAuthController$1.failure(OAuthController.java:94)
E/Twitter (22181): 	at com.twitter.sdk.android.core.internal.oauth.OAuth1aService$1.failure(OAuth1aService.java:191)
E/Twitter (22181): 	at com.twitter.sdk.android.core.Callback.onResponse(Callback.java:42)
E/Twitter (22181): 	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
E/Twitter (22181): 	at android.os.Handler.handleCallback(Handler.java:938)
E/Twitter (22181): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/Twitter (22181): 	at android.os.Looper.loop(Looper.java:223)
E/Twitter (22181): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/Twitter (22181): 	at java.lang.reflect.Method.invoke(Native Method)
E/Twitter (22181): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/Twitter (22181): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/flutter (22181): PlatformException(400, Failed to get request token, null, null)
